#!/usr/bin/env sh

export DISPLAY=:0.0

xset b off

[ -e "/etc/X11/xinit/xinitrc.d/50-systemd-user.sh" ] && source "/etc/X11/xinit/xinitrc.d/50-systemd-user.sh"
xrdb -load $HOME/.config/X11/xresources


session=${1:-awesome}
case $session in
    awesome   ) exec /usr/bin/awesome >> ~/.cache/awesome/stdout 2>> ~/.cache/awesome/stderr;;
    hyprland  ) exec hyprland;;
    *         ) exec $1;;
esac
